export const usersData = [
    {
        id:1,
        firstName:"yusuf",
        lastName:"demir",
        city:"grave",
        age:31,
        creditCardNumber:"123456",
        type:"customer"
    },
    {
        id:8,
        firstName:"kazim",
        lastName:"kozalak",
        city:"grave",
        age:31,
        creditCardNumber:"123456",
        type:"customer"
    },
    {
        id:2,
        firstName:"yavuz",
        lastName:"demir",
        city:"grave",
        age:"asf2a",
        creditCardNumber:"654321",
        type:"customer"

    },
    {
        id:3,
        firstName:"sevcan",
        lastName:"demir",
        city:"grave",
        age:30,
        salary:"888888",
        type:"employee"
    },
    {
        id:4,
        firstName:"abuzittin",
        lastName:"mubizittin",
        city:"at",
        age:98,
        salary:"5555555",
        type:"employee"
    },
    {
        id:5,
        firstName:"babus",
        lastName:"kabus",
        city:"esek",
        age:115,
        salary:"6546468",
        type:"emmplye"
    }
]